### ISSUE TITLE
sql for edasich

### ISSUE THREAD

**Issue by linhsolar** [tuwiendsg/EPICS#26]
In the sql script: some hardcore appear.  why do i need them?

 -- ----------------------------
--  Records of `Event`
-- ----------------------------
BEGIN;
INSERT INTO `Event` VALUES ('1', 'daf1', 'Thu 2014.10.09 at 02:35:59 AM UTC', '[SensorY  - Value: 18699.6583591] ; [SensorY  - Value: 16088.9995849] ; ', 'EMERGENCY'), ('
2', 'daf1', 'Thu 2014.10.09 at 02:36:34 AM UTC', '[SensorY  - Value: 18523.2182418] ; [SensorY  - Value: 10249.5530907] ; [SensorY  - Value: 18131.0640982] ; ', 'WARNING'
), ('3', 'daf1', 'Thu 2014.10.09 at 02:36:34 AM UTC', '[SensorY  - Value: 18131.0640982] ; [SensorY  - Value: 18523.2182418] ; ', 'EMERGENCY');
COMMIT;

**Comment by jun-nguyen** [comment]
removed data in CloudLyra.sql
